# ./github/actions/my-action/action.yml
name: "Send notification on slack commits channel"
description: "Sends a custom notification to the internal slack commits channel"
inputs:
  emoji:
    description: "The emoji related to this repo"
    required: false
    default: ":question:"
  slack-webhook-url:
    description: 'The Slack webhook URL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Send commit update on commits channel with curl
      run: |
        branch_name="${GITHUB_REF#refs/heads/}"
        message=$(jq -n \
        --arg actor "${{ github.actor }}" \
        --arg repo "${{ github.repository }}" \
        --arg emoji "${{ inputs.emoji }}" \
        --arg branch "$branch_name" \
        --arg commit_msg "${{ github.event.head_commit.message }}" \
        --arg sha "${{ github.sha }}" \
        --arg run_id "${{ github.run_id }}" \
        --arg webhook "${{ inputs.slack-webhook-url }}" \
        '{
          text: "New commit on \($repo) by \($actor)!",
          blocks: [
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: "\($emoji) *\($actor)* pushed a new commit on *\($repo)* (branch: \($branch)): \($commit_msg)"
              }
            },
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: "Go to: <https://github.com/\($repo)|repository> or <https://github.com/\($repo)/commit/\($sha)|commit> or <https://github.com/\($repo)/actions/runs/\($run_id)|action>"
              }
            }
          ]
        }')
        curl -X POST -H 'Content-type: application/json' --data "$message" "${{ inputs.slack-webhook-url }}"
      shell: bash
